export const NODE_TYPES = {
  INPUT: "input",
  PROCESS: "process",
  VALIDATE: "validate",
  OUTPUT: "output",
  ERROR: "error",
};

export const COLORS = {
  INPUT: "#10b981",
  PROCESS: "#3b82f6",
  VALIDATE: "#f59e0b",
  OUTPUT: "#10b981",
  ERROR: "#ef4444",
  EDGE: "#6b7280",
  HIGHLIGHT: "#06b6d4",
};

export const STEPS = [
  { id: 1, title: "LLM 파이프라인: 정확한 AI의 비결", section: "intro", duration: 30, content: { heading: "LLM 파이프라인: 정확한 AI의 비결", description: "음식점 비유로 배우는 환각 방지 기술", analogy: "음식점이 정확한 주문을 배달하는 방식과 AI 파이프라인의 원리를 배웁니다", keyPoint: "AI도 음식점처럼 단계별 검증을 거쳐야 거짓을 말하지 않습니다" }, visualization: { type: "title", nodes: [], edges: [] } },
  { id: 2, title: "일반 AI의 문제: 환각(Hallucination)", section: "intro", duration: 60, content: { heading: "일반 AI는 거짓을 마치 사실인 것처럼 말합니다", description: "일반 AI는 데이터가 없어도 그럴듯한 거짓을 생성합니다", analogy: "거짓말하는 웨이터가 주문을 받고 아무 확인 없이 대충 넘기는 것처럼", keyPoint: "AI가 거짓을 말하는 이유는 데이터 검증 없이 순진하게 텍스트만 생성하기 때문입니다" }, visualization: { type: "hallucination", nodes: [{ id: "question", type: "input", x: 100, y: 300, label: "사용자" }, { id: "llm", type: "process", x: 300, y: 300, label: "LLM" }, { id: "false", type: "error", x: 500, y: 300, label: "거짓" }], edges: [{ id: "e1", from: "question", to: "llm" }, { id: "e2", from: "llm", to: "false" }] } },
  { id: 3, title: "skeleton-analysis: 10계층 검증 시스템", section: "intro", duration: 60, content: { heading: "음식점처럼 단계별 검증으로 거짓을 막습니다", description: "음식점은 주문, 주방, 검사, 배달 의 각 단계에서 확인합니다", analogy: "웨이터, 주방장, 위생 검사관, 배달원이 각자 확인하는 음식점 프로세스", keyPoint: "10계층 검증: 우회, 제약, 합의, 강제필터, 재필터, LLM팩트체크, 코드팩트체크, 템플릿폴백, 래핑검증, 강제템플릿" }, visualization: { type: "overview", nodes: [{ id: "s", type: "input", x: 100, y: 300, label: "질문" }, { id: "p0", type: "process", x: 250, y: 150, label: "P0" }, { id: "p1", type: "process", x: 250, y: 300, label: "P1" }, { id: "v", type: "validate", x: 450, y: 300, label: "검증" }, { id: "e", type: "output", x: 600, y: 300, label: "답변" }], edges: [{ id: "e1", from: "s", to: "p0" }, { id: "e2", from: "s", to: "p1" }, { id: "e4", from: "p0", to: "v" }, { id: "e5", from: "p1", to: "v" }, { id: "e7", from: "v", to: "e" }] } },
  { id: 4, title: "Phase 0: 빠른 경로", section: "basic", duration: 90, content: { heading: "첫 번째 검증", description: "간단한 질문이면 LLM 호출 0회", analogy: "메뉴판에 있으면 즉시 제공", keyPoint: "키워드 매칭으로 LLM 호출을 회피합니다" }, visualization: { type: "fast_path", nodes: [{ id: "q", type: "input", x: 100, y: 300, label: "질문" }, { id: "k", type: "validate", x: 300, y: 300, label: "키워드" }, { id: "a", type: "output", x: 500, y: 300, label: "답변" }], edges: [{ id: "e1", from: "q", to: "k" }, { id: "e3", from: "k", to: "a" }] } },
  { id: 5, title: "Phase 1: 3개 SQL과 투표", section: "basic", duration: 120, content: { heading: "두 번째 검증", description: "3개 LLM이 SQL을 만들고 투표합니다", analogy: "여러 주방장의 의견을 수집하여 최선을 선택", keyPoint: "다수결 투표로 최적 SQL을 선택합니다" }, visualization: { type: "voting", nodes: [{ id: "q", type: "input", x: 100, y: 300, label: "Q" }, { id: "l0", type: "process", x: 300, y: 100, label: "L0" }, { id: "l1", type: "process", x: 300, y: 300, label: "L1" }, { id: "l2", type: "process", x: 300, y: 500, label: "L2" }, { id: "v", type: "validate", x: 500, y: 300, label: "투표" }, { id: "s", type: "output", x: 700, y: 300, label: "SQL" }], edges: [{ id: "e1", from: "q", to: "l0" }, { id: "e2", from: "q", to: "l1" }, { id: "e3", from: "q", to: "l2" }, { id: "e7", from: "l0", to: "v" }, { id: "e8", from: "l1", to: "v" }, { id: "e9", from: "l2", to: "v" }, { id: "e10", from: "v", to: "s" }] } },
  { id: 6, title: "Phase 1: 안전 필터 주입", section: "basic", duration: 90, content: { heading: "세 번째 검증", description: "LLM SQL에 안전 필터를 강제로 추가합니다", analogy: "위생 검사관이 위험 재료를 감시", keyPoint: "코드 레벨에서 필터를 강제 적용합니다" }, visualization: { type: "filter_gate", nodes: [{ id: "si", type: "process", x: 100, y: 300, label: "SQL" }, { id: "g", type: "validate", x: 300, y: 300, label: "필터" }, { id: "so", type: "output", x: 500, y: 300, label: "SQL" }], edges: [{ id: "e1", from: "si", to: "g" }, { id: "e5", from: "g", to: "so" }] } },
  { id: 7, title: "Phase 2: DB 실행 및 필터", section: "process", duration: 90, content: { heading: "네 번째 검증", description: "SQL 실행 후 결과를 다시 필터링합니다", analogy: "배달 온 음식을 한 번 더 확인", keyPoint: "DB 결과도 클라이언트에서 재검증합니다" }, visualization: { type: "db_execution", nodes: [{ id: "sql", type: "process", x: 100, y: 300, label: "SQL" }, { id: "db", type: "process", x: 300, y: 300, label: "DB" }, { id: "r", type: "output", x: 500, y: 300, label: "결과" }], edges: [{ id: "e1", from: "sql", to: "db" }, { id: "e2", from: "db", to: "r" }] } },
  { id: 8, title: "Phase 3: 답변 생성", section: "process", duration: 90, content: { heading: "다섯 번째 검증", description: "정제된 데이터로 LLM이 답변을 생성합니다", analogy: "제한된 재료로만 요리합니다", keyPoint: "DB 결과를 입력으로 주므로 거짓을 줄입니다" }, visualization: { type: "answer_generation", nodes: [{ id: "d", type: "input", x: 100, y: 300, label: "데이터" }, { id: "l0", type: "process", x: 300, y: 150, label: "T0" }, { id: "l1", type: "process", x: 300, y: 450, label: "T3" }, { id: "a0", type: "output", x: 500, y: 150, label: "A1" }, { id: "a1", type: "output", x: 500, y: 450, label: "A2" }], edges: [{ id: "e1", from: "d", to: "l0" }, { id: "e2", from: "d", to: "l1" }, { id: "e3", from: "l0", to: "a0" }, { id: "e4", from: "l1", to: "a1" }] } },
  { id: 9, title: "Phase 4: 이중 팩트체크", section: "process", duration: 120, content: { heading: "여섯 번째/일곱 번째 검증", description: "LLM과 코드가 답변의 숫자를 검증합니다", analogy: "주문과 정확히 일치하는지 확인", keyPoint: "숫자 하나하나가 DB에서 나온 데이터인지 검증합니다" }, visualization: { type: "factcheck", nodes: [{ id: "a", type: "input", x: 100, y: 300, label: "답변" }, { id: "d", type: "input", x: 100, y: 500, label: "데이터" }, { id: "c", type: "validate", x: 300, y: 300, label: "검증" }, { id: "s", type: "output", x: 500, y: 300, label: "점수" }], edges: [{ id: "e1", from: "a", to: "c" }, { id: "e2", from: "d", to: "c" }, { id: "e7", from: "c", to: "s" }] } },
  { id: 10, title: "Phase 5: 템플릿 폴백", section: "validate", duration: 90, content: { heading: "여덟 번째 검증", description: "점수 0.8 미만이면 템플릿 사용", analogy: "음식이 이상하면 기본 메뉴 제공", keyPoint: "의심스러운 답변은 안전한 템플릿으로 전환합니다" }, visualization: { type: "template_fallback", nodes: [{ id: "s", type: "input", x: 100, y: 300, label: "점수" }, { id: "b", type: "validate", x: 300, y: 300, label: "분기" }, { id: "l", type: "output", x: 500, y: 150, label: "LLM" }, { id: "t", type: "output", x: 500, y: 450, label: "템플릿" }], edges: [{ id: "e1", from: "s", to: "b" }, { id: "e2", from: "b", to: "l" }, { id: "e3", from: "b", to: "t" }] } },
  { id: 11, title: "Phase 5: 자연어 래핑", section: "validate", duration: 90, content: { heading: "아홉 번째/열 번째 검증", description: "자연어 재작성 + 수치 보존 검증", analogy: "음식을 예쁜 플레이팅으로 제시", keyPoint: "래핑 후에도 숫자를 재검증합니다" }, visualization: { type: "wrapping", nodes: [{ id: "sel", type: "input", x: 100, y: 300, label: "답변" }, { id: "w", type: "process", x: 300, y: 300, label: "래핑" }, { id: "c", type: "validate", x: 500, y: 300, label: "검증" }, { id: "f", type: "output", x: 700, y: 300, label: "답변" }], edges: [{ id: "e1", from: "sel", to: "w" }, { id: "e2", from: "w", to: "c" }, { id: "e4", from: "c", to: "f" }] } },
  { id: 12, title: "사례 1: 빠른 경로", section: "case", duration: 120, content: { heading: "여찬혁의 기록", description: "단순 선수 이름 질문 처리", analogy: "자주 주문하는 고객은 빠르게 처리", keyPoint: "아무도 LLM을 부르지 않았습니다" }, visualization: { type: "case_fast", nodes: [{ id: "q", type: "input", x: 100, y: 300, label: "Q" }, { id: "k", type: "validate", x: 250, y: 300, label: "KW" }, { id: "n", type: "process", x: 400, y: 300, label: "Name" }, { id: "db", type: "process", x: 550, y: 300, label: "DB" }, { id: "t", type: "process", x: 700, y: 300, label: "Tmpl" }, { id: "a", type: "output", x: 850, y: 300, label: "Ans" }], edges: [{ id: "e1", from: "q", to: "k" }, { id: "e2", from: "k", to: "n" }, { id: "e3", from: "n", to: "db" }, { id: "e4", from: "db", to: "t" }, { id: "e5", from: "t", to: "a" }] } },
  { id: 13, title: "사례 2: 풀 파이프라인", section: "case", duration: 150, content: { heading: "12월 평균 기록 분석", description: "Phase 0 실패 후 전체 파이프라인 통과", analogy: "특별한 주문 처리 과정", keyPoint: "모든 검증을 거쳐야 신뢰할 수 있는 답변이 됩니다" }, visualization: { type: "case_full", nodes: [{ id: "q", type: "input", x: 50, y: 300, label: "Q" }, { id: "p0", type: "validate", x: 150, y: 300, label: "P0" }, { id: "p1", type: "process", x: 250, y: 150, label: "P1" }, { id: "p2", type: "process", x: 350, y: 200, label: "P2" }, { id: "p3", type: "process", x: 450, y: 200, label: "P3" }, { id: "p4", type: "validate", x: 550, y: 200, label: "P4" }, { id: "p5", type: "process", x: 650, y: 200, label: "P5" }, { id: "a", type: "output", x: 750, y: 200, label: "A" }], edges: [{ id: "e1", from: "q", to: "p0" }, { id: "e2", from: "p0", to: "p1" }, { id: "e4", from: "p1", to: "p2" }, { id: "e6", from: "p2", to: "p3" }, { id: "e7", from: "p3", to: "p4" }, { id: "e8", from: "p4", to: "p5" }, { id: "e9", from: "p5", to: "a" }] } },
];
export default { NODE_TYPES, COLORS, STEPS };
